name: Cancel Running Actions on PR Close

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
jobs:
  cancel-other-runs:
    runs-on: ubuntu-latest

    permissions:
      actions: write  # Required to cancel workflows
      contents: read

    steps:
      - name: Cancel previous runs
        uses: actions/github-script@v7
        with:
          script: |
            const currentRunId = process.env.GITHUB_RUN_ID;
            const workflowId = process.env.GITHUB_WORKFLOW;

            const runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
              workflow_id: workflowId,
              branch: context.payload.pull_request.head.ref,
              status: 'in_progress'
            });

            for (const run of runs.data.workflow_runs) {
              if (run.id != currentRunId) {
                console.log(`Cancelling run ${run.id}`);
                await github.rest.actions.cancelWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: run.id
                });
              }
            }
